name: shell_script_codegen
description: A code generation package for minifying and parameterizing shell scripts
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.5.4
  build_config: ^1.1.2
  source_gen: ^2.0.0
  analyzer: ^7.5.4
  meta: ^1.17.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.5.4