name: shell_script_codegen
description: A code generation package for parameterizing shell scripts
version: 1.0.0
homepage: https://github.com/xxxOVALxxx/shell_script_codegen
repository: https://github.com/xxxOVALxxx/shell_script_codegen
issue_tracker: https://github.com/xxxOVALxxx/shell_script_codegen/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.5.4
  build_config: ^1.1.2
  source_gen: ^2.0.0
  analyzer: ^7.5.4
  meta: ^1.17.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.5.4

topics:
  - code-generation
  - shell-scripts
  - build-runner
  - source-gen